### ISSUE TITLE
请教下重复计数目前有什么实际应用呢？

### ISSUE THREAD

**Issue by gao-shi** [Xiaodomgdomg/Deep-Temporal-Repetition-Counting#2]
看了你们的工作，很棒！今年的CVPR google也有一篇重复计数的，感觉研究这方面的逐渐变多了，想请教下目前重复计数有什么实际应用吗？

**Comment by Xiaodomgdomg** [comment]
As mentioned in our paper: The repetition analysis is explored as an auxiliary cue to other video analysis applications, such as cardiac and respiratory signal recover [16], pedestrian detection [22], 3D reconstruction [15, 24], and camera calibration [11].

Moreover, we can also consider the applications in sport analysis, AI industry, etc.

**Comment by gao-shi** [comment]
Thank you very much!
